services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_AUTH_METHOD=md5
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - the-pound-pg:/var/lib/postgresql/data

volumes:
  the-pound-pg:
    driver: local
